### ISSUE TITLE
Release 0.1.5 in maven central

### ISSUE THREAD

**Issue by eddumelendez** [tjni/captain-hook#5]
Release 0.1.5 was done but it is not in maven central yet. Can you make it available, please?

**Comment by eddumelendez** [comment]
@tjni any update?

**Comment by tjni** [comment]
I am very sorry, I had to take time off.

Thank you for the ping. I've published it to Maven Central now. I hope this works for you!

**Comment by eddumelendez** [comment]
It is published now https://repo1.maven.org/maven2/com/github/tjni/captainhook/captain-hook/0.1.5/

Thank you so much! I really don't like to do this but since I saw the release on github done then I was just expecting for the artifact in maven central. Now, we will use the dependency directly 😁 Thanks one more time!
